import { __makeTemplateObject } from "tslib";
import { css } from "@emotion/react";
import { getColorStyle, getSpacingStyle } from "../../theme";
export var root = function () { return css(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  input {\n    visibility: hidden;\n    position: absolute;\n    z-index: 0;\n  }\n\n  .loader {\n    width: 24px;\n    height: 24px;\n    border: 5px solid #4682b4;\n    border-bottom-color: transparent;\n    border-radius: 50%;\n    display: inline-block;\n    box-sizing: border-box;\n    animation: rotation 1s linear infinite;\n  }\n\n  @keyframes rotation {\n    0% {\n      transform: rotate(0deg);\n    }\n    100% {\n      transform: rotate(360deg);\n    }\n  }\n"], ["\n  input {\n    visibility: hidden;\n    position: absolute;\n    z-index: 0;\n  }\n\n  .loader {\n    width: 24px;\n    height: 24px;\n    border: 5px solid #4682b4;\n    border-bottom-color: transparent;\n    border-radius: 50%;\n    display: inline-block;\n    box-sizing: border-box;\n    animation: rotation 1s linear infinite;\n  }\n\n  @keyframes rotation {\n    0% {\n      transform: rotate(0deg);\n    }\n    100% {\n      transform: rotate(360deg);\n    }\n  }\n"]))); };
export var table = function (theme) {
    return css(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n    width: 100%;\n    border-collapse: collapse;\n\n    th,\n    td {\n      vertical-align: middle;\n      border-bottom: 1px solid;\n      ", ";\n      ", "\n    }\n\n    tr td:last-child {\n      padding-right: 0;\n      min-width: 100px;\n    }\n  "], ["\n    width: 100%;\n    border-collapse: collapse;\n\n    th,\n    td {\n      vertical-align: middle;\n      border-bottom: 1px solid;\n      ", ";\n      ", "\n    }\n\n    tr td:last-child {\n      padding-right: 0;\n      min-width: 100px;\n    }\n  "])), getSpacingStyle("padding", 3, theme), getColorStyle("border-color", "grey300", theme));
};
export var nameColumn = function () { return css(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n  width: 100px;\n  white-space: nowrap;\n"], ["\n  width: 100px;\n  white-space: nowrap;\n"]))); };
export var actionsColumn = function () { return css(templateObject_4 || (templateObject_4 = __makeTemplateObject(["\n  width: 1px;\n  white-space: nowrap;\n"], ["\n  width: 1px;\n  white-space: nowrap;\n"]))); };
var templateObject_1, templateObject_2, templateObject_3, templateObject_4;
//# sourceMappingURL=FileSelector.styles.js.map